### ISSUE TITLE
Please add option to disable full screen

### ISSUE THREAD

**Issue by Tatsh** [bemusic/bemuse#256]
Since the app does not open in full screen, this is a complete surprise when it happens. Chrome no longer has any option to block full screen.

Could you provide an option in _Options_? Based on the source, it seems like I have to spoof my user agent so it won't trigger.

On my system (a 2012 MacBook Pro 15") with an nVidia GeForce 650M, full screen performance is far worse than non-full screen.

**Comment by dtinth** [comment]
Thanks for sending in the issue. Right now, [you can disable fullscreen by setting the `BEMUSE_NO_FULLSCREEN` flag](https://github.com/bemusic/bemuse/blob/e79971c175756dd1b0d9632bcf5a949c63344df7/src/devtools/query-flags.js#L12-L14) to `1`:

https://bemuse.ninja/?BEMUSE_NO_FULLSCREEN=1

I’d love to implement this as an option in the Options screen, so I’ll leave this issue open.

**Comment by Tatsh** [comment]
Thanks. I saw that file and did not realise those were literally strings looked for in the query string.
