### ISSUE TITLE
Implement autoplay mode.

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#410]
This will allow BMS and especially bmson authors to capture the screen and publish they autoplay videos onlike (similar to [these](https://www.youtube.com/channel/UCgq4rVycLhEeDsvHiQe0AXg) [channels](https://www.youtube.com/user/ams198686).
- The result screen should be skipped when autoplay mode is activated. This means ranking is skipped entirely.
- Keysounds should be automatically played.

**Comment by kytwb** [comment]
I'm taking this. Any hints where I should start to look at?

**Comment by dtinth** [comment]
Thanks! :)

As for __how to activate the autoplay mode.__ I haven’t figured this out either. 😛 

The simplest way would be to Alt+Click on the play button. Another way is to toggle it in-game (e.g. pressing <kbd>F8</kbd> like StepMania). Yet another way is to have a toolbar button in the music selection screen. Also please feel free to come up with your own idea.
