### ISSUE TITLE
Update Travis CI and CircleCI to use Yarn instead of npm

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#413]
Now our CI scripts are using npm. To make the build process faster we want to change to use Yarn…

Use `yarn.lock` from commit     7d50f41.

**Comment by SharkChips** [comment]
I'm on it!

**Comment by SharkChips** [comment]
Completed in #418

**Comment by winniehell** [comment]
@dtinth It looks like this is solved. Could you close it or remove the hacktoberfest label?

**Comment by dtinth** [comment]
Sure, thanks for the reminder. :)

On Mon, Oct 31, 2016, 03:27 Winnie <notifications@github.com> wrote:

@dtinth <https://github.com/dtinth> It looks like this is solved. Could you
close it or remove the hacktoberfest label?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/bemusic/bemuse/issues/413#issuecomment-257176651>, or mute
the thread
