### ISSUE TITLE
Please add option to disable scratch

### ISSUE THREAD

**Issue by shouh** [bemusic/bemuse#425]
Hello, i am shouh and japanese bms hobbyist.

Is there a option to disable scratch? (I tried to find it, but could not... :sweat: )
If do not, I desire it.

I especially love DJMAX, and it does not have a scratch. So, no scratch is user friendly for like of me.

Thank you for reading. :smile:

**Comment by dtinth** [comment]
Hello!

Of course, you can disable scratch.

1. From the __music selection screen,__ at the bottom right corner, you’ll see the “Options” button.

  ![image](https://cloud.githubusercontent.com/assets/193136/21103354/b5c01b5c-c0b4-11e6-81c1-920ced848557.png)

2. You can disable the scratch here:

  ![image](https://cloud.githubusercontent.com/assets/193136/21103384/c861119e-c0b4-11e6-8066-399344d42171.png)

If this has solved your problem, please kindly close the issue. If there are any other questions related to this problem, please feel free to ask.

Thanks!

**Comment by shouh** [comment]
Thank you for responce.

I thought above disabled selection is only to change the view. I will try it!
