### ISSUE TITLE
Stage invisible in play screen.

### ISSUE THREAD

**Issue by Agrrox** [bemusic/bemuse#429]
After loading songs I can't see any parts of stage but I can start song and play.
Stage is visible in Safari.
Browser: Chrome: Version 55.0.2883.95 (64-bit)
Machine: Macbook Pro 2009 Mid 17 inch
OS: 10.11.6

EDIT: I tried to completely uninstall all chrome files from system and reinstall it again. Still same results.

![screen shot 2016-12-26 at 04 45 47](https://cloud.githubusercontent.com/assets/10901821/21475034/facf8e22-cb26-11e6-9141-4650aed97df6.png)

**Comment by dtinth** [comment]
@Agrrox That’s very strange. I’m not sure but it may be that WebGL is not working?

From this StackOverflow question, [WebGl will not work in Chrome](http://stackoverflow.com/questions/21916930/webgl-will-not-work-in-chrome), can you try running Chrome with `--ignore-gpu-blacklist`?

**Comment by Agrrox** [comment]
I think there might be some bug with WebGL in Chrome or 9600M GT is probably black listed. Tried to use `Override software rendering list` flag in chrome but then the game is unplayable.
