### ISSUE TITLE
Upgrade to React 16.

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#437]
**Note:** Please make sure that the app starts and the game is playable before submitting a PR. Please feel free to break this task into multiple PRs (e.g. change `React.PropTypes` to `prop-types`).

**Comment by resir014** [comment]
Hey, it's me again! I'll take a look at this later today.

**Comment by abdullateef97** [comment]
ia this issue stilll open

**Comment by dtinth** [comment]
@abdullateef97 Yes, the work done in #441 did not resolve this issue.

For the PR to be accepted please make sure the app starts and the gameplay is working properly.

Please feel free to break this task into multiple PRs (e.g. change `React.PropTypes` to `prop-types`).

**Comment by resir014** [comment]
@dtinth I'm currently doing so now. Once done I can try my hand in converting all instances of `React.createClass()` to pure class components.

Just gotta have to get through the ropes of having to run this project on a Windows machine (yay WSL!)

**Comment by resir014** [comment]
Now that #442 is merged, I can begin all the heavy work on converting the code from `React.createClass()` to either class components, SFCs, or `PureComponent`s, depending on context. I'll let you know when everything's good and ready to test.

For reference, I'm following most of the guides outlined [here](https://blog.discordapp.com/lessons-from-migrating-a-large-codebase-to-react-16-e60e49102aa6).

### Some caveats

By default [JavaScript's context binding](https://medium.freecodecamp.org/react-binding-patterns-5-approaches-for-handling-this-92c651b5af56) means that the way handler functions are implemented with `React.createClass` have to be converted to bind the `this` context. Currently I'm leaning more towards wrapping them in arrow functions (e.g. `<button onClick={() => this.handleClick()} />`) than arbitralily adding `.bind(this)` on every handler function.

Unfortunately, I'm not comfortable with using `jscodeshift` or its derivatives, which means that I will have to find and replace these classes/functions one by one.

### Some good-to-haves

**I know that this is quite unrelated to this issue, and not a requirement per se, but just my two cents.**

I think this project would really benefit from static type checking, to allow for easy refactoring, as well as many other code quality improvements. Moving forward, it would really help in the long run, whenever stuff changes again on later React versions.

Though unfortunately, I'm not familiar with Flow at all, as I'm more leaning towards TypeScript in my other projects, so I'd probably only be capable to help when you're thinking about migrating to TS.

**Comment by dtinth** [comment]
@resir014 Wow, sounds like a plan! Thanks a lot for helping!

### About autobinding

Usually, what I do is this:

- If it is a DOM element, I prefer arrow functions, e.g. `<button onClick={e => ...} />`. Since it is already a leaf element, we don’t need to worry about breaking `shouldComponentUpdate`.

- If it is a custom component, I prefer to bind using arrow function as a public class field: `onClick = (e) => { ... }`, as this is the safest way to migrate without having to worry about creating a new function every render, thus potentially breaking `shouldComponentUpdate` down the road.

About codemods, I usually run them one file at a time, followed by an `eslint --fix`. I wouldn’t run it on the whole project at once as well :)

### About types

I agree that moving forward I should consider adding some types. I also lean towards TypeScript as Microsoft is pushing it forward a lot with first class support in VSCode and stuff.

**Comment by resir014** [comment]
@dtinth Awesome!

I also finally converted the rest of the classes through codemod. I put the (still-unfinished) PR up for now.

**Comment by resir014** [comment]
We're finally ready to upgrade! I'll also see if there are some other dependencies that I could update as well while I make sure everything works.

@dtinth should I wait until #446 is merged? Or do I go forward with this?

**Comment by dtinth** [comment]
@resir014 That’s awesome!

I think it is OK to upgrade to React 16 right away because the game engine doesn’t depend on React.

**Comment by dtinth** [comment]
By the way, since ESLint has improved a lot it may also be a good time to transition to more vanilla JavaScript Standard Style. What do you think?

**Comment by resir014** [comment]
@dtinth Yep, that would be great as well!

**Comment by resir014** [comment]
Ack, seems like some dependencies are preventing the app to work on React 16. Couldn't even get past the loading screen.

![image](https://user-images.githubusercontent.com/5663877/31673411-55b32966-b389-11e7-8319-83c41084e827.png)

**Comment by resir014** [comment]
Since everything's all merged to React 16, I think we're ready to close this?

**Comment by dtinth** [comment]
Yep, thanks for your help!! 😄
