### ISSUE TITLE
Latency calibration should mute menu music while open

### ISSUE THREAD

**Issue by hashdang** [bemusic/bemuse#449]
It makes calibration a lot harder when two songs are playing at once.

**Comment by dtinth** [comment]
Thanks for the report!

I will put this on Hacktoberfest for now. :)

## Steps to reproduce

1. Go to https://bemuse.ninja, __enter game__, and select a mode (e.g. Keyboard Mode). Menu music should start playing.

2. Open the __Options__ screen (button located at bottom right corner). An options dialog should appear.

3. Click the __Calibrate__ button. Another window should appear. While this window is open, the menu music should pause. Once the window is closed, the menu music can resume playing.
