### ISSUE TITLE
Turntable joystick axis strange behavior?

### ISSUE THREAD

**Issue by cyberkitsune** [bemusic/bemuse#450]
Hey,

I've been trying to use a DJDAO controller to play bemuse, and as it is a directinput controller, all is working well with the buttons, but the turntable axis behavior does not work with the game.

Bemuse appears to trigger the turntable when the axis goes from negative to positive or vice versa, crossing 0 being the trigger. However,  when you scratch the turntable on the controller, it just increases or decreases the axis value as you spin it.

Could a feature be implemented that just tracks retaliative changes to the turntable axis value over time instead of across zero to trigger the control? (With a configurable threshold would be preferable)

**Comment by dtinth** [comment]
@cyberkitsune  I also have a DJ DAO controller, but it operates in positive/negative fashion. I think my controller came before the INFINITAS mode is introduced. Can you try switching your controller to LR2 mode? The manual is here: https://www.gamo2.com/en/firmware/

**Comment by cyberkitsune** [comment]
@dtinth I have the latest firmware. Thanks for the tip about LR2 mode, when operating in LR2 mode however, bemuse only detects the positive X axis, and not the negative one. As a result, the turntable only works when spinning one direction.

I have confirmed in the system controller config that the turntable is functioning properly otherwise.

**Comment by dtinth** [comment]
@cyberkitsune Sorry for the lack of response. Since I don’t have the controller with the new firmware, I am unable to debug it.

If you can fix this problem in the game, a PR is welcome. 😄
