### ISSUE TITLE
Upgrade to webpack 4.0 alpha (with javascript/esm mode)

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#453]
The changelog of each webpack 4 alpha, and notable parts relevant to this project:

  - alpha.0 https://github.com/webpack/webpack/issues/6064

      - With `--mode`, our webpack config can be simplified.
      - Module type `javascript/esm` allows more strict bundling (e.g. checks for nonexistent imports), and more predictable behavior when importing non-ESM modules.

  - alpha.1 https://github.com/webpack/webpack/issues/6132

  - alpha.2 https://github.com/webpack/webpack/issues/6179

      - Faster uglification

**Comment by resir014** [comment]
[Webpack 4 beta](https://medium.com/webpack/webpack-4-beta-try-it-today-6b1d27d7d7e2) is now released, and if I have the time, I could work on it this week. 🚀
