### ISSUE TITLE
Upgrade to React 16.2 and explore the possibility to use JSX Fragments

### ISSUE THREAD

**Issue by resir014** [bemusic/bemuse#454]
[React 16.2](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) is finally out and it has support for JSX Fragments.

First thing in order is to upgrade the React version on this project. Then we could explore which parts could JSX Fragments be implemented.

**Comment by dtinth** [comment]
Thanks for reporting the issue! Agreed!

**Comment by dtinth** [comment]
Closed via #457
