### ISSUE TITLE
Big Docs Update™

### ISSUE THREAD

**Issue by resir014** [bemusic/bemuse#473]
I've thrown this around for a while, but haven't really gotten around to it, so putting this up here for future reference.

As we may already know, the Sphinx-based docs hasn't been building properly since forever due to the codedoc generation failing. As proposed on #468, I'm going to outline a possible plan for a docs revamp.

* Ditch Sphinx, and figure out a new documentation system to use. ([Docusaurus](https://docusaurus.io/) perhaps?)
* The above means that the documentation files (`*.rst`) might have to be converted to Markdown.
* Convert any old codedoc-based documentation blocks into valid [JSDoc](http://usejsdoc.org/).
* Update any possibly-outdated bits in the documentation.

I will start looking into this once I finished with Webpack 4.

**Comment by resir014** [comment]
I've begun working on this. Will put a PR in a bit.

**Comment by dtinth** [comment]
Awesome, thanks!
