### ISSUE TITLE
Bundle an ogg/vorbis decoder for use in Safari/iOS

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#509]
From discord chat

https://ptb.discordapp.com/channels/427735173606670336/449913763445997590/509737133343375361

Safari and iOS does not support ogg/vorbis files.

- We have to generate both `.ogg` and `.m4a` files, resulting in larger bundle.
- With same bitrate, free `.m4a` encoder doesn’t sound as good as Apple’s encoder, and sounds worse than `.ogg` with same bitrate.
- Apple’s `.m4a` encoder runs only on Mac/Windows and is proprietary.

## Prior art

- https://github.com/petamoriken/oggVorbisToWave.js
- https://github.com/hajimehoshi/ebiten/issues/623
- https://github.com/audiocogs/aurora.js + https://github.com/audiocogs/vorbis.js

## Impact

- Can make bemuse packs on Linux
- 2x smaller

## Cons

- Larger game bundle
- May be slower at runtime

**Comment by hajimehoshi** [comment]
Note that Ebiten now uses stbvobis.js which is stb_vorbis.h port to JavaScript (Wasm): https://github.com/hajimehoshi/stbvorbis.js
