### ISSUE TITLE
Weird long notes (holds) in 3D mode

### ISSUE THREAD

**Issue by ghost** [bemusic/bemuse#515]
They are scary: 
![clipboarder 2018 12 08-004](https://user-images.githubusercontent.com/25438100/49683013-0c84bc80-facf-11e8-9e60-b23d7d7ec723.png)

**Comment by dtinth** [comment]
Yup, that's the look of long notes in 3D mode for now.

Suggestions are welcome, but since this game uses a 2d game engine, long notes has to be constructed out of repeated parts
