### ISSUE TITLE
Notes offset

### ISSUE THREAD

**Issue by RkEclair** [bemusic/bemuse#531]
In my env, hitsounds shows late but my latency has set 0ms.
I think It sounds just at -20ms, but I can't set negative latency in Advanced Settings.
Why can't I set a negative latency?

**Comment by dtinth** [comment]
“Latency” here means the amount of time *after* you press a button and you hear the sound back from the speaker. The more time it takes for audio to go to the speaker, the more latency there is. That’s why audio latency cannot be negative.

The game compensates for that by playing some sounds ahead-of-time by the latency number specified.

- If your results shows more “late” judgments, then latency should be increased.
- If your results shows more “early” judgments, then latency should be decreased. But if latency is already zero, that probably means you may be accustomed to games that have higher audio latency, which makes you hit the keys too early.

**Comment by RkEclair** [comment]
Sorry, I want the way to "come the notes earlier" or "play other sounds and movie later".
I'm using the wireless headphone, so the sounds is later than rendered.
It seems that it cannot be solved in latency. I'll change the title.

**Comment by dtinth** [comment]
Setting a positive latency will cause sounds to play earlier. For wireless headphones, this is sometimes as high as 200ms.

After the game, try opening the "detailed accuracy" popup. Note the "Mean" value. It should say something like "+58ms (late)". In this case try adding 58ms to the latency settings.

Let me know if this helps.

**Comment by RkEclair** [comment]
I noticed that the cause is to tune with the sound that I heard, so I'll close this issue.
Thank you for your kindness.
