### ISSUE TITLE
Refactoring: Replace `updeep` with `immer`

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#704]
## Background

Bemuse used the `updeep` library, but after some experience in other projects I think using `immer` leads to more readable code.

## Task

- Replace `updeep` with `immer`.
- Your PR should migrate all usage of code that uses `updeep` and replace it with `immer`. In `bemuse/package.json`, `updeep` should be removed from dependencies, and latest version of `immer` added.
- All automated checks should pass.

## Hacktoberfest

If you would like to work on this task, please write a comment stating your intent. We will then assign the issue to you. To ensure continuity, the issue will be unassigned after 3 days of inactivity — so please keep us updated.

**Comment by dtinth** [comment]
@aadityasinha-dotcom The issue is now yours, thank you! 🙏

**Comment by aadityasinha-dotcom** [comment]
@dtinth I have added the latest version of `immer` in the `bemuse/package.json` and removed the `updeep` from the dependencies.
