### ISSUE TITLE
Fix leaderboard and account login/creation

### ISSUE THREAD

**Issue by BelugaHaechi** [bemusic/bemuse#830]
Currently (7/22/2023) the leaderboard and account login/creation functions in the game do not work. Leaderboards are always loading, while when creating an account is attempted, an server error is raised (501). 

Are there any plans to fix this? Bemuse is a really fun and convenient BMS simulator, and I hope it can become better :)

**Comment by Touhou2017** [comment]
I second this.
Would love to make an account, so I don't have to screenshot my scores every time I play.

**Comment by Touhou2017** [comment]
IT'S BACK!!

**Comment by dtinth** [comment]
I feel dumb. I should have restarted the server a long time ago because apparently it fixes the issue. 😂 

Glad to hear that the issue is resolved now and sorry for the inconvenience.

**Comment by BelugaHaechi** [comment]
yay

**Comment by DJTOMATO** [comment]
Seems the error is back?
