### ISSUE TITLE
[Research] Audio-video offset synchronization and audio+input delay calibration

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#87]
Assumptions
-----------------

- Response time is zero. When the player hears the sound or sees that the note hits the judgement area, he/she pushes the button immediately.
- When the game emits the sound, it takes time ___S___ until the player hears it. (Audio latency)
- When the game renders the display, it takes time ___D___ until the player sees it. (Video latency)
- When the player hits the button, it takes time ___I___ until the computer recognizes it. (Input latency)

Findings
----------

- It is impossible to measure/calibrate the values of ___S___, ___D___, ___I___ separately.
- But it is possible to find these values:
    - ___S___+___I___ (Audio + input latency)
    - ___D___+___I___ (Video + input latency)
    - ___S___-___D___ (Audio-video offset)

Methods
----------

### Calibration

1. Measure ___A___ = ___S___+___I___

    This is the time it takes from when the sound is emitted to when the computer recognizes the button press. This means that when computer emits sound at time ___t___, the computer will receive button press at time ___t'___=___t___+___A___. To compensate, when button press is received at time ___t'___, judgement must be performed for time ___t'___-___A___=___t___.

2. Measure ___B___ = ___S___-___D___

    This is the audio/video offset. This can be done by letting user adjust the value until audio and video are in sync. With this value, we adjust the display to display notes in time ___t___+___B___.

     - When computer emits sound at time ___t___, player will hear it at time ___t___+___S___.
     - When computer emits graphics at time ___t___+___B___, player will see it at time ___t___+___D___+___S___-___D___ = ___t___+___S___, thus proving that the user will find audio and video to be in sync.

### Gameplay

- `sound(t)`: At time ___t___, emit sound as usual.
- `display(t+B)`: At time ___t___, emit graphic in sync with the sound.
- `judgment(t-A)`: Judge notes ___A___ unit of time behind the sound emission.

Auto-Keysounds
---------------------

This is a problem if the value of ___A___ is large. If the player hit the note at the correct time, they will hear delayed keysounds.

That's why for most keysounded music games, user has to press the button significantly before the sound is emitted. Examples include DJMAX Technika and Tone Sphere.

Therefore, we have to play keysound for the player, so that the player hears at the correct time. This is called "Auto-sound" in Open2Jam.

### Enabling AutoSound

AutoSound will only be enabled when value of ___A___ is significantly large. I'd say 16 milliseconds. A warning message should appear in synchronization dialog saying that AutoSound has been enabled to compensate for audio delay.

### AutoSound Mechanics

- Each player has a playing state ___p___, defaults to __true__.
    - This state is __true__ when player is actively playing and __false__ when player isn't playing any note.
    - When user doesn't play any note, we don't want keysounds to be automatically emitted, so we stop autosound mechanism until user hits a note again, setting ___p___ back to __true__.
- Each note ___n___ will have a keysound state ___k_(_n_)__, defaults to "NONE".
- If player hits the note ___n___ before it is sounded (___k_(_n_)__ is "NONE"):
    - Emit the keysound.
    - Set ___k_(_n_)__ to "EMITTED"
    - Set ___p___ to __true__
- If it's the time for the note (___t___ = ___t_(_n_)__) and ___k_(_n_)__ is "NONE" and the player is playing (___p___ is __true__):
    - Emit the keysound.
    - Set ___k_(_n_)__ to "EMITTED"
- If the note is missed and ___k_(_n_)__ is "EMITTED":
    - Stop the keysound.
    - Set ___p___ to __false__.

**Comment by dtinth** [comment]
Calibrating the value of ___A___
--------------------------------------------

### Methods

- Play a song and instruct user to press the button on every beat.
- Record at least 56 samples of ___A___ (time that keypress is registered - time that sound is emitted)
- Analyze the recorded samples.

**Comment by dtinth** [comment]
From the data analysis, we have found that the delay on average is 13.96 ms. This is very small, and we are pretty safe to use 0ms delay as default value.

The average standard deviation of the delay is 21.57 milliseconds. This means that on average, we are 99% confident that the actual delay is within 6.59 of the obtained mean.

This shows that our method is quite effective.

Our advisor, @jittat, suggested that we can try to reduce the number of required samples, so that the calibration process would become shorter.

----

@Nachanok 

Try to simulate by performing the same experiment, but only using the first ___n___ samples. Find the smallest value of ___n___ such that the average resulting 99% confidence interval is less than 10 milliseconds.

**Comment by Nachanok** [comment]
Mean and Standard Deviation  
- https://docs.google.com/spreadsheets/d/19ZJjIvLHhHUv6WkkCrK-fif-9eaevjfoqTT65jpOvnE/edit?usp=sharing  
  
Mean and Standard Deviation (length 50)  
- https://docs.google.com/spreadsheets/d/1napp26yIzTn-jZjnYchcL7BX-9ADih5VW_ikUamWLWQ/edit?usp=sharing

**Comment by dtinth** [comment]
@Nachanok Thank you! I think it's better for you to focus on the skin's code. I'll continue from here. :smile:

**Comment by dtinth** [comment]
I've done some changes to our calculation:

Since our sample is going to be small, and we only have sample standard deviation (we don't know the _population_ standard deviation), [I used T-score instead of Z-score](http://www.statisticshowto.com/when-to-use-a-t-score-vs-z-score/).

Some communication problems also led to the sample data being incorrectly trimmed.

**Comment by dtinth** [comment]
Here's the confidence interval results by trying various values of ___n___. For each value of ___n___, each person's tapping pattern is truncated to the first ___n___ taps.

| n | 90% | 95% | 99% |
| ---:| --------: | --------: | --------: |
| 9999 | 3.940332 | 4.723988 | 5.654889 | 6.303091 |
| 50 | 4.623089 | 5.554879 | 6.670214 | 7.453008 |
| 49 | 4.613531 | 5.544791 | 6.660451 | 7.444172 |
| 48 | 4.884783 | 5.869317 | 7.047786 | 7.874891 |
| 47 | 4.927309 | 5.921907 | 7.113446 | 7.950470 |
| 46 | 4.976760 | 5.982942 | 7.189458 | 8.037804 |
| 45 | 5.037827 | 6.058083 | 7.282660 | 8.144571 |
| 44 | 5.107284 | 6.143473 | 7.388458 | 8.265672 |
| 43 | 5.138891 | 6.183502 | 7.439988 | 8.326315 |
| 42 | 5.137204 | 6.183623 | 7.443767 | 8.333759 |
| 41 | 5.494494 | 6.611390 | 7.954823 | 8.902482 |
| 40 | 5.514859 | 6.638205 | 7.990986 | 8.946406 |
| 39 | 5.581117 | 6.720470 | 8.094260 | 9.065787 |
| 38 | 5.661806 | 6.820375 | 8.219230 | 9.209872 |
| 37 | 5.737184 | 6.914181 | 8.337363 | 9.346757 |
| 36 | 5.784753 | 6.974789 | 8.416010 | 9.439870 |
| 35 | 5.761313 | 6.950079 | 8.392228 | 9.418560 |
| 34 | 6.284942 | 7.577877 | 9.143717 | 10.256106 |
| 33 | 6.369274 | 7.683485 | 9.277815 | 10.412451 |
| 32 | 6.447250 | 7.781886 | 9.404011 | 10.560649 |
| 31 | 6.690453 | 8.080363 | 9.773102 | 10.982627 |
| 30 | 6.598211 | 7.974306 | 9.653954 | 10.856885 |
| 29 | 6.629881 | 8.018521 | 9.717638 | 10.937592 |
| 28 | 6.577397 | 7.961592 | 9.659865 | 10.882624 |
| 27 | 7.366215 | 8.909082 | 10.796907 | 12.152353 |
| 26 | 7.480202 | 9.054390 | 10.985765 | 12.376359 |
| 25 | 7.561358 | 9.161038 | 11.129612 | 12.551396 |
| 24 | 7.778887 | 9.434326 | 11.478393 | 12.959830 |
| 23 | 7.907150 | 9.601103 | 11.700677 | 13.228292 |
| 22 | 8.114986 | 9.866621 | 12.047054 | 13.640529 |
| 21 | 8.375315 | 10.198808 | 12.479895 | 14.155370 |
| 20 | 9.080049 | 11.039995 | 13.479732 | 15.262709 |
| 19 | 9.291662 | 11.314664 | 13.845325 | 15.704115 |
| 18 | 9.602974 | 11.714706 | 14.371431 | 16.334215 |
| 17 | 10.136242 | 12.391364 | 15.247396 | 17.371805 |
| 16 | 10.484268 | 12.849220 | 15.867984 | 18.131513 |
| 15 | 10.148322 | 12.475783 | 15.474883 | 17.745374 |
| 14 | 9.879257 | 12.191519 | 15.205670 | 17.514447 |

Each song section is 28 hits. Therefore, with only one section, we are 98% sure that our observed mean will be within 10ms of the actual audio+input delay.

To be more sure (99%), I think obtaining just 35 samples are good enough.

**Comment by dtinth** [comment]
I think the preliminary research has obtained satisfactory result.

The task of implementing them in the game will be another issue.
